language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - nosetests
  - behave

after_success: coveralls

notifications:
  email:
    recipients:
      - mezuro-core@lists.ime.usp.br
    on_success: change
    on_failure: always
