language: python
python:
  - "2.7"

install: 'pip install -r requirements.txt'

script: nosetests

notifications:
  email:
    recipients:
      - mezuro-core@lists.ime.usp.br
    on_success: change
    on_failure: always