language: python
python:
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.rvm
    - cache/kalibro_configurations
    - cache/kalibro_processor

install:
  # Install Ruby manually since the Kalibro script assumes it is already there
  - rvm install 2.2.3
  - rvm use 2.2.3 --default
  - rvm @global do gem install bundler
  # Kalibro Install script
  - git clone https://github.com/mezuro/kalibro_install.git -b v4.0
  - ANALIZO_VERSION=none KALIBRO_PROCESSOR_VERSION='v1.1.1' KALIBRO_CONFIGURATIONS_VERSION='v1.2.0' CACHE_DIR=$PWD/cache ./kalibro_install/install.sh
  # Python dependencies
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - nosetests
  - behave --no-capture --no-capture-stderr

after_success: coveralls

before_cache:
  - rm -rf $HOME/.cache/pip/log
  - rm -rf $HOME/.rvm/log

notifications:
  email:
    recipients:
      - mezuro-core@lists.ime.usp.br
    on_success: change
    on_failure: always
